#ifdef USE_MODULE_COMMON
DECLARE_MODULE(h264)
DECLARE_MODULE(rtcp)
#endif //USE_MODULE_COMMON

#ifdef USE_MODULE_H264
DECLARE_MODULE(rtmp)
#endif //USE_MODULE_H264

#ifdef USE_MODULE_RTCP
DECLARE_MODULE(nack)
#endif //USE_MODULE_RTCP

